import datetime

def generate_cam(data, score, category, decision, amount, rate, reasons):
    """
    Returns a formatted markdown string of the Credit Appraisal Memo
    """
    
    date_str = datetime.datetime.now().strftime("%B %d, %Y")
    
    reasons_bullets = "\n".join([f"- {r}" for r in reasons])
    
    cam = f"""
# Credit Appraisal Memo (CAM)
**Generated by IntelliCredit AI | Date: {date_str}**

---

### 1. BORROWER PROFILE
- **Entity Type:** Corporate LLC
- **Industry Sector Focus:** Technology / Services
- **Sector Risk Assigned:** {data['sector_risk']}
- **Legal/Compliance Track:** {data['litigations']} pending litigation items detected.

### 2. FINANCIAL ANALYSIS (LTM)
Provides an overview dynamically extracted from uploaded GST and financial statements.

- **Assessed Revenue:** ${data.get('revenue', 0):,} 
- **Y-o-Y Revenue Growth:** {data.get('revenue_growth', 0)}%
- **Assessed Total Debt:** ${data.get('debt', 0):,}
- **EBITDA:** ${data.get('ebitda', 0):,}
- **Interest Coverage Ratio (ICR):** {data.get('icr', 0)}x
- **Total Net Worth:** ${data.get('net_worth', 0):,}

### 3. AI RISK EVALUATION
The enterprise credit risk engine processed NLP sentiment logic and financial ratios.

- **IntelliCredit Risk Score:** {score} / 100
- **Overall Bracket Designation:** {category}
- **Market Sentiment Matrix:** {'Predictably Positive' if data['sentiment']>0.75 else 'Neutral / Weak'}

### 4. EXECUTIVE LOAN RECOMMENDATION
Based strictly on the deterministic weights mapped within the AI scoring agent.

- **Decision Flow:** **{decision}**
- **Recommended Facility Amount:** {amount}
- **Suggested Interest Rate:** {rate}

**Key Driving Factors:**
{reasons_bullets}

---
*Disclaimer: This is an automatically generated AI credit appraisal memo and must be reviewed by the chief risk officer prior to final loan underwriting execution.*
    """
    return cam.strip()
